In [2]:
!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

--2024-12-26 21:02:03--  https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8002::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1115394 (1.1M) [text/plain]
Saving to: 'input.txt'

input.txt           100%[===================>]   1.06M  --.-KB/s    in 0.05s   

2024-12-26 21:02:03 (21.0 MB/s) - 'input.txt' saved [1115394/1115394]



In [3]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [4]:
print('length of dataset in chars: ', len(text))

length of dataset in chars:  1115394


In [5]:
# Get head of dataset
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [12]:
# build a list of each unique characters that occur in the dataset
charsSet = set(text)
print(len(charsSet))
print(charsSet)

charsList = list(charsSet)
print(charsList)

alphabet = sorted(charsList)
print(alphabet)
alphabetLength = len(alphabet)

# to display nicely our dataset characters
print()
print(''.join(alphabet))
print('length of unique chars: ', len(alphabet))

65
{'?', '.', 'O', 'X', 'R', 'i', 'p', '\n', 'h', 'G', ' ', 'Y', 'I', 'd', 'T', 'l', 'g', 'k', 's', 'H', 'y', 'U', '&', '$', 'n', 'w', 'C', 'm', 'B', 'r', 'a', 'L', 'b', 't', ':', 'v', 'F', 'A', 'J', ';', 'D', 'Q', '!', 'c', 'P', 'q', ',', 'Z', 'N', 'M', 'V', 'u', 'K', '-', 'o', 'f', "'", 'S', 'j', 'z', 'x', '3', 'E', 'W', 'e'}
['?', '.', 'O', 'X', 'R', 'i', 'p', '\n', 'h', 'G', ' ', 'Y', 'I', 'd', 'T', 'l', 'g', 'k', 's', 'H', 'y', 'U', '&', '$', 'n', 'w', 'C', 'm', 'B', 'r', 'a', 'L', 'b', 't', ':', 'v', 'F', 'A', 'J', ';', 'D', 'Q', '!', 'c', 'P', 'q', ',', 'Z', 'N', 'M', 'V', 'u', 'K', '-', 'o', 'f', "'", 'S', 'j', 'z', 'x', '3', 'E', 'W', 'e']
['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


 !$&',-.3:;?AB

In [13]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [15]:
# We now want to encode the entire dataset
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [18]:
# We do split dataset for train and validation sets
n = int(0.9*len(data))
trainData = data[:n]
validationData = data[n:]

In [25]:
chuckSize = 8
trainData[:chuckSize+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [26]:
x = trainData[:chuckSize]
y = trainData[1:chuckSize+1]
for t in range(chuckSize):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target is {target}")

when input is tensor([18]) the target is 47
when input is tensor([18, 47]) the target is 56
when input is tensor([18, 47, 56]) the target is 57
when input is tensor([18, 47, 56, 57]) the target is 58
when input is tensor([18, 47, 56, 57, 58]) the target is 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target is 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target is 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target is 58


In [27]:
torch.manual_seed(1337)
batchSize = 4 # how many independent sequences will we process in parallel?
chuckSize = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = trainData if split == 'train' else validationData
    ix = torch.randint(len(data) - chuckSize, (batchSize,))
    x = torch.stack([data[i:i+chuckSize] for i in ix])
    y = torch.stack([data[i+1:i+chuckSize+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batchSize): # batch dimension
    for t in range(chuckSize): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input is [44, 53

In [40]:
# build the model and generate next logit to the sentence

import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, alphabetSize):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.tokenEmbeddingTable = nn.Embedding(alphabetSize, alphabetSize)

    def forward(self, idx, targets=None):
        #idx and targets are both (B, T) tensor of integers
        logits = self.tokenEmbeddingTable(idx) # (B, T, C)
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)
        
        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel(alphabetLength)
out, loss = model(xb, yb)
print(out.shape)
print(loss)

print(decode(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 65])
tensor(4.8786, grad_fn=<NllLossBackward0>)

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [41]:
# train the model
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

In [46]:
# training loop
batchSize = 32
for steps in range(10000):
    xb, yb = get_batch('train')

    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    print(loss.item())

3.7458245754241943
3.6640820503234863
3.702449083328247
3.5994691848754883
3.6177873611450195
3.6064648628234863
3.6632843017578125
3.6675870418548584
3.6528513431549072
3.709588050842285
3.627749443054199
3.575915575027466
3.6474523544311523
3.6581995487213135
3.638275623321533
3.667233943939209
3.692593812942505
3.600438117980957
3.5805344581604004
3.712693214416504
3.695218563079834
3.659806251525879
3.6587765216827393
3.697878837585449
3.581294298171997
3.666944742202759
3.710739850997925
3.614734411239624
3.584317445755005
3.6219077110290527
3.6710448265075684
3.5316832065582275
3.609124183654785
3.5991389751434326
3.528642416000366
3.6293892860412598
3.5244290828704834
3.6396946907043457
3.653947114944458
3.5364491939544678
3.6176748275756836
3.6420798301696777
3.558375835418701
3.592052936553955
3.690396308898926
3.5904088020324707
3.7710983753204346
3.5889410972595215
3.591643810272217
3.5874180793762207
3.629249334335327
3.58882212638855
3.6336188316345215
3.622912883758545
3.

In [47]:
print(decode(model.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


Sll;
O: pa heore 'ga llis?-sur inidind;
t me rthay n thavee
Sw s serer Fofow.
Houspathe t:
Mind fit.
